### ISSUE TITLE
使用独立的MongoDB

### ISSUE THREAD

**Issue by chengpeixin** [jinfeijie/yapi#1]
你好，我使用的我自己的数据库，在启动时需要进行验证，这部分在环境变量中可以配置么？

**Comment by jinfeijie** [comment]
@chengpeixin 
down完代码后，修改config.json里面的db的内容为如下格式，数据改成你自己的。

```
  "db": {
    "servername": "127.0.0.1",
    "DATABASE": "yapi",
    "port": 27017,
    "user": "test1",
    "pass": "test1",
    "authSource": ""
  },

```
修改docker-compose.yml文件为
```
version: '2.1'
services:
  yapi:
    image: mrjin/yapi:latest
#    build: ./
    container_name: yapi
    environment:
      - VERSION=1.5.6
      - LOG_PATH=/tmp/yapi.log
      - HOME=/home
      - PORT=3000
      - ADMIN_EMAIL=<你的管理员邮箱>
#      - DB_SERVER=<mongoDB的地址>
#      - DB_NAME=<对应的DBName>
#      - DB_PORT=<mongoDB的端口>
    # restart: always
    ports:
      - 127.0.0.1:3000:3000
    volumes:
      - ~/data/yapi/log/yapi.log:/home/vendors/log # log dir
    entrypoint: "bash  entrypoint.sh"
    networks:
      - back-net
networks:
  back-net:
    external: true
```
