### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by u5de6** [jinfeijie/yapi#37]
用的是最新的镜像  ”Last pushed 19 hours ago by [mrjin](https://hub.docker.com/u/mrjin)“

Error: container_linux.go:367: starting container process caused: exec: "bash /wait-for-it.sh mongo:27017 -- entrypoint.sh": stat bash /wait-for-it.sh mongo:27017 -- entrypoint.sh: no such file or directory: OCI not found

**Comment by jinfeijie** [comment]
找一下你的bash文件在哪里
替换下这一行 https://github.com/jinfeijie/yapi/blob/master/docker-compose.yml#L22

**Comment by u5de6** [comment]
因为已经有其他mongo的服务了   我是改了service的名字和端口了的   按理说应该不会影响吧

```
version: '2.1'
services:
  yapi:
    image: mrjin/yapi:latest
    # build: ./
    container_name: yapi
    environment:
      - VERSION=1.10.2
      - LOG_PATH=/tmp/yapi.log
      - HOME=/home
      - PORT=3000
      - ADMIN_EMAIL=test@test.com
      - DB_SERVER=dmongo
      - DB_NAME=yapi
      - DB_PORT=37017
    # restart: always
    ports:
      - 127.0.0.1:3000:3000
    volumes:
      - /a_dev/dev_yapi/log/yapi.log:/home/vendors/log # log dir
    depends_on:
      - brmongo
    entrypoint: "bash /wait-for-it.sh dmongo:37017 -- entrypoint.sh"
    networks:
      - back-net
  dmongo:
    image: mongo
    container_name: dmongo
    # restart: always
    ports:
      - 127.0.0.1:37017:27017
    volumes:
      - /a_dev/dev_yapi/mongodb:/data/db #db dir
    networks:
      - back-net
networks:
  back-net:
    external: true
```

bash文件路径改了也不行    去掉了直接执行/wait-for-it.sh dmongo:37017 -- entrypoint.sh也有问题
