### ISSUE TITLE
内网部署数据认证失败

### ISSUE THREAD

**Issue by 853270563** [jinfeijie/yapi#42]
![image](https://user-images.githubusercontent.com/40133848/225534564-eb71736c-a9dc-4fa9-96a1-295e8bb46cd8.png)
我在公网部署没有问题，在内网部署会出现上面的错误信息。

**Comment by jinfeijie** [comment]
> ![image](https://user-images.githubusercontent.com/40133848/225534564-eb71736c-a9dc-4fa9-96a1-295e8bb46cd8.png) 我在公网部署没有问题，在内网部署会出现上面的错误信息。

看去是网络问题
进容器里面telnet看下是否能连上mongo的地址

**Comment by 853270563** [comment]
在容器里面是可以ping通的，可以加你联系方式吗





---原始邮件---
发件人: "fj ***@***.***&gt;
发送时间: 2023年3月16日(周四) 下午2:39
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [jinfeijie/yapi] 内网部署数据认证失败 (Issue #42)




  
 我在公网部署没有问题，在内网部署会出现上面的错误信息。
  
看去是网络问题的。
 进容器里面telnet看下是否能连上mongo的地址

**Comment by 853270563** [comment]
> > ![image](https://user-images.githubusercontent.com/40133848/225534564-eb71736c-a9dc-4fa9-96a1-295e8bb46cd8.png) 我在公网部署没有问题，在内网部署会出现上面的错误信息。
> 
> 看去是网络问题 进容器里面telnet看下是否能连上mongo的地址

数据库设置的密码是多少？我用客户端连接试试

**Comment by jinfeijie** [comment]
@853270563 
没有设置密码
如果需要用客户端链接，记得暴露mongodb的端口

**Comment by jinfeijie** [comment]
上传一下你的部署yaml文件，我帮你看下。
看上去是没在一个docker网络里面

注意一下
```
networks:
  back-net:
    external: true
```


`- DB_SERVER=mongo` 是否与mongo的服务名字一致
```
 yapi:
    image: mrjin/yapi:latest
    # build: ./
    container_name: yapi
    environment:
      - VERSION=1.10.2
      - LOG_PATH=/tmp/yapi.log
      - HOME=/home
      - PORT=3000
      - ADMIN_EMAIL=test@test.com
      - DB_SERVER=mongo
      - DB_NAME=yapi
      - DB_PORT=27017
    # restart: always
    ports:
      - 127.0.0.1:3000:3000
    volumes:
      - ~/data/yapi/log/yapi.log:/home/vendors/log # log dir
    depends_on:
      - mongo
    entrypoint: "bash /wait-for-it.sh mongo:27017 -- entrypoint.sh"
    networks:
      - back-net
```
